#!/usr/bin/env bash
# oc-kit.sh [--check] — load the .claude kit into OpenCode 2.x: its agents and commands under
# .opencode/, and its always-on rules plus prompts/AGENT_BRIEF.md into AGENTS.md.
# Why each output exists (probes 2026-09-30, OpenCode 2.0.18): 2.x reads .claude/skills natively, but
# not .claude/agents, whose `tools:` it does not know (it wants `mode:` and `permission:`). It loads
# AGENTS.md and IGNORES opencode.json's `instructions` key (a sentinel in AGENTS.md was seen, one in an
# `instructions` file was not). A house file of the same name (no generated line) wins and is kept.
# --check exits 1 when a generated file is missing, stale or orphaned, so a kit bump cannot drift.
# Interim: the kit's own `devil export opencode` (slice X1) replaces this script once it lands.
# Ponytail: permissions are derived from three tool names only (Write/Edit, Bash, WebFetch); a kit
# agent listing some other tool gets no rule for it and inherits opencode.json's allow. Path-scoped
# rules become one pointer line each: nothing makes the model read the file before a matching edit.
set -euo pipefail
shopt -s nullglob
cd "$(git rev-parse --show-toplevel)"
mark='<!-- generated by scripts/orch/oc-kit.sh from'
case ${1:-} in
  '' | --check) check=${1:-} rc=0 ;;
  *)
    echo "usage: oc-kit.sh [--check]  exit 0 in sync or written, 1 stale (--check), 2 misuse" >&2
    exit 2
    ;;
esac
[[ -d .claude/agents ]] || {
  echo "oc-kit: .claude is empty; run git submodule update --init .claude" >&2
  exit 2
}

frontmatter() { awk 'NR==1 && /^---$/ {f=1; next} f && /^---$/ {exit} f' "$1"; }
body() { awk 'NR==1 && /^---$/ {f=1; next} f && /^---$/ {f=0; b=1; next} b' "$1"; }
description() {
  frontmatter "$1" | awk '/^description:/ {d=1; sub(/^description: *>?-? */, ""); s=$0; next}
    d && /^  / {sub(/^ +/, ""); s = s (s == "" ? "" : " ") $0; next} {d=0} END {print s}'
}
permissions() {
  local tools
  tools=$(frontmatter "$1" | sed -n 's/^tools: *//p')
  [[ $tools == *Edit* || $tools == *Write* ]] || echo "  edit: deny"
  [[ $tools == *Bash* ]] || echo "  bash: deny"
  [[ $tools == *WebFetch* ]] || echo "  webfetch: deny"
}
rule_paths() { frontmatter "$1" | awk '/^ *- / {gsub(/^ *- *"?|"$/, ""); printf "%s%s", (n++ ? ", " : ""), $0}'; }
render() { # <kind: agents|commands> <source file>
  local perm
  printf -- '---\ndescription: >-\n  %s\n' "$(description "$2")"
  if [[ $1 == agents ]]; then
    echo "mode: all"
    perm=$(permissions "$2")
    [[ -z $perm ]] || printf 'permission:\n%s\n' "$perm"
  fi
  printf -- '---\n%s %s; edit the source and rerun it. -->\n' "$mark" "$2"
  body "$2"
}
render_agents_md() {
  local rule scoped
  printf '%s prompts/AGENT_BRIEF.md and .claude/rules/*.md; edit those and rerun it. -->\n' "$mark"
  cat prompts/AGENT_BRIEF.md
  for rule in .claude/rules/*.md; do
    if [[ -z $(rule_paths "$rule") ]]; then printf '\n' && cat "$rule"; fi
  done
  printf '\n# Path-scoped rules: read the file before you edit a path it names\n\n'
  for rule in .claude/rules/*.md; do
    scoped=$(rule_paths "$rule")
    if [[ -n $scoped ]]; then printf -- "- \`%s\`: %s\n" "$rule" "$scoped"; fi
  done
}
sync_file() { # <destination>; the rendered content arrives on stdin
  local dst=$1
  if [[ -f $dst ]] && ! grep -qF "$mark" "$dst"; then return 0; fi
  if [[ $check == --check ]]; then
    cmp -s "$dst" - || {
      echo "stale: $dst"
      rc=1
    }
  else
    mkdir -p "$(dirname "$dst")"
    cat >"$dst"
  fi
}
for kind in agents commands; do
  for src in .claude/"$kind"/*.md; do sync_file ".opencode/$kind/${src##*/}" < <(render "$kind" "$src"); done
  for dst in .opencode/"$kind"/*.md; do
    if ! grep -qF "$mark" "$dst" || [[ -f .claude/$kind/${dst##*/} ]]; then continue; fi
    if [[ $check == --check ]]; then
      echo "orphan: $dst"
      rc=1
    else rm -- "$dst"; fi
  done
done
sync_file AGENTS.md < <(render_agents_md)
exit "$rc"
