//! The D1 measurement document: the template, the table and the conclusion drawn from it.

use graph_wasm::probe::{FUNCTIONS, RANDOM_PER_FUNCTION, SPECIALS};

/// Differing-bit-pattern counts for one function.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct Counts {
    /// Inputs swept.
    pub inputs: usize,
    /// On the native target, `std` and `libm` disagree.
    pub native_std_vs_libm: usize,
    /// On wasm32, `std` and `libm` disagree.
    pub wasm_std_vs_libm: usize,
    /// `std` on one target against `std` on the other.
    pub std_native_vs_wasm: usize,
    /// `libm` on one target against `libm` on the other; non-zero is a stop.
    pub libm_native_vs_wasm: usize,
    /// Largest distance, in ULPs, between native and wasm32 `std`.
    pub max_ulp_std_native_vs_wasm: u64,
}

const REPORT: &str = r#"# D1 — `std` vs `libm` transcendentals, native vs wasm32

Generated by `graph-cli determinism-probe`; do not edit by hand. Re-run to refresh:

```sh
docker run --rm -v "$PWD:/w" ge-rust cargo run -p graph-cli -- determinism-probe
```

Toolchain: {tools}. wasm32 artifact `graph_wasm.wasm` sha256 `{wasm_sha}`.

## The sweep

Defined once in `crates/graph-wasm/src/probe.rs` and executed unchanged on both targets:
natively inside `graph-cli`, and as wasm32 (built with `--features probe`) through
`harness/wasm-run.mjs` under Node. The two runs are checked to have swept bit-identical inputs
before any output is compared.

- **Specials** ({specials} magnitudes, each with its negation, plus ±0): denormals (`5e-324`,
  `1e-320`, `2.225e-309`, the largest subnormal), `1e-300` … `0.5`, values around 1.0
  (`0.999999`, `1 − ε`, `1`, `1 + ε`, `1.000001`), and large magnitudes up to `f64::MAX`.
  Each function keeps only the specials inside its domain (`ln_1p`: x > −1; `ln`: x > 0).
  `pow` pairs each magnitude with exponents `0.5`, `−3`, `40`, and a negative base with `3`;
  `atan2` pairs every signed special with `±1` and `±0`.
- **Seeded pseudo-random inputs**: {random} per function from xorshift64 seeded
  `0x5EED_D1D1_0000_0001 ^ function index`, built from raw bit patterns so whole binades are
  covered: `ln_1p` over (−1, 0) and binades 2⁻⁶⁰…2⁶⁰; `ln` over every normal binade; `exp`
  uniform on [−745, 709]; `sin`/`cos` signed, binades 2⁻³⁰…2³⁰; `pow` base in 2⁻³⁰…2³⁰ with
  exponent uniform on [−40, 40]; `atan2` both arguments signed in 2⁻³⁰…2³⁰.

## Differing bit patterns

{table}
- *native std≠libm* — on the native target, `std` and `libm` disagree.
- *wasm32 std≠libm* — the same, on wasm32.
- *std native≠wasm32* — the claim D1 was written on: `std` on one target against `std` on the other.
- *libm native≠wasm32* — the property D1 relies on; any non-zero value here is a stop.

## Conclusion

{conclusion}

## Limits

Ponytail: this is a sampler, not the whole f64 domain. An input on which the implementations round
differently but that the sweep never visits goes uncounted, so the probe can only **under-report**
divergence — the dangerous direction. Escape hatch: raise `RANDOM_PER_FUNCTION` or add the suspect
input to `SPECIALS`. The sweep is f64 only; the `f32` variants (`log1pf`, …) are not probed.
"#;

pub fn render(counts: &[Counts], tools: &str, wasm_sha: &str) -> String {
    let mut table = String::from(
        "| function | inputs | native std≠libm | wasm32 std≠libm | std native≠wasm32 | libm native≠wasm32 | max ULP std native↔wasm32 |\n|---|---:|---:|---:|---:|---:|---:|\n",
    );
    for (name, c) in FUNCTIONS.iter().zip(counts) {
        table.push_str(&format!(
            "| `{name}` | {} | {} | {} | {} | {} | {} |\n",
            c.inputs,
            c.native_std_vs_libm,
            c.wasm_std_vs_libm,
            c.std_native_vs_wasm,
            c.libm_native_vs_wasm,
            c.max_ulp_std_native_vs_wasm
        ));
    }
    let std_split: usize = counts.iter().map(|c| c.std_native_vs_wasm).sum();
    let libm_split: usize = counts.iter().map(|c| c.libm_native_vs_wasm).sum();
    [
        ("{tools}", tools.to_owned()),
        ("{wasm_sha}", wasm_sha.to_owned()),
        ("{specials}", SPECIALS.len().to_string()),
        ("{random}", RANDOM_PER_FUNCTION.to_string()),
        ("{table}", table),
        ("{conclusion}", conclusion(std_split, libm_split)),
    ]
    .into_iter()
    .fold(REPORT.to_owned(), |doc, (key, value)| {
        doc.replace(key, &value)
    })
}

fn conclusion(std_split: usize, libm_split: usize) -> String {
    let libm = if libm_split == 0 {
        "`libm` is bit-identical between native and wasm32 on every input of the sweep, which is what D1 relies on.".to_string()
    } else {
        format!(
            "**`libm` itself differs between native and wasm32 on {libm_split} inputs. D1 as written is insufficient — stop and report.**"
        )
    };
    let std = if std_split == 0 {
        "`std` also agreed across targets on this sweep, so D1 is **cheap insurance**, not a measured necessity: the constraint stands, with this measurement as its recorded reason.".to_string()
    } else {
        format!(
            "`std` differs between native and wasm32 on **{std_split}** inputs, so D1 is **confirmed by measurement**: a motor calling `std` transcendentals would hash differently on the two targets."
        )
    };
    format!("{libm}\n\n{std}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn conclusion_follows_the_two_split_counts() {
        let clean = conclusion(0, 0);
        assert!(clean.contains("bit-identical") && clean.contains("cheap insurance"));
        let confirmed = conclusion(5, 0);
        assert!(confirmed.contains("on **5** inputs") && confirmed.contains("confirmed"));
        assert!(!confirmed.contains("insufficient"));
        let broken = conclusion(0, 2);
        assert!(broken.contains("on 2 inputs") && broken.contains("stop and report"));
        assert!(!broken.contains("bit-identical"));
    }

    #[test]
    fn render_fills_every_placeholder_and_one_row_per_function() {
        let row = |n| Counts {
            inputs: 10 + n,
            native_std_vs_libm: 1,
            wasm_std_vs_libm: 2,
            std_native_vs_wasm: n,
            libm_native_vs_wasm: 0,
            max_ulp_std_native_vs_wasm: 7,
        };
        let counts: Vec<Counts> = (0..FUNCTIONS.len()).map(row).collect();
        let doc = render(&counts, "rustc 9.9", "feed");
        assert!(
            !doc.contains('{') || doc.contains("```sh"),
            "unfilled placeholder"
        );
        for key in [
            "{tools}",
            "{wasm_sha}",
            "{specials}",
            "{random}",
            "{table}",
            "{conclusion}",
        ] {
            assert!(!doc.contains(key), "{key} left in the document");
        }
        assert!(doc.contains("Toolchain: rustc 9.9.") && doc.contains("`feed`"));
        assert!(doc.contains("| `ln` | 11 | 1 | 2 | 1 | 0 | 7 |"));
        assert!(doc.contains(&format!("({} magnitudes", SPECIALS.len())));
        assert!(doc.contains(&format!("{RANDOM_PER_FUNCTION} per function")));
        assert!(doc.contains("on **21** inputs"), "sum of 0..7 std splits");
    }
}
