//! The fixture's own generator: rewriting the `graph` half of
//! `fixtures/ingest/expected-graph.json` from the derivation.
//!
//! A committed expected file that is regenerated by hand is a fixture that pins nothing.
//! This is the other half of `the_committed_graph_is_exactly_what_the_derivation_produces`:
//! with `GM_WRITE_INGEST_GRAPH=1` set, that test rewrites the file and reports what it
//! wrote; without it, it compares. The gate row and the human command are the same test.
//!
//! Only the `graph` member's **text** is replaced. The `ingest` half is written by
//! `harness/write-expected-ingest.mjs` in JavaScript, and re-serializing it from Rust
//! would make the file's formatting a function of whichever generator ran last — which is
//! exactly the drift this one committed file exists to prevent.

use graph_contract::ingest::{JsonValue, read_value, to_json_value};

/// The committed fixture, relative to the crate root (`CARGO_MANIFEST_DIR` is
/// `<repo>/crates/graph-core`, so two levels up is the repo). `convergence`'s
/// `include_str!` compiles the file in, so a renamed one is a build failure rather than
/// an empty check.
const FIXTURE: &str = "/../../fixtures/ingest/expected-graph.json";

/// The env var the committed failure messages already name, so the command printed in a
/// failing test is the command that works.
pub(super) const ENV: &str = "GM_WRITE_INGEST_GRAPH";

/// Whether this run was asked to rewrite the fixture.
pub(super) fn requested() -> bool {
    std::env::var_os(ENV).is_some()
}

/// Rewrite the fixture's `graph` member to `produced` — the derivation's canonical text —
/// or leave the file untouched. Returns the file's new whole text, so the caller reports
/// the write it made rather than leaving a silent one behind.
pub(super) fn write_graph(produced: &str) -> std::io::Result<String> {
    let path = format!("{}{FIXTURE}", env!("CARGO_MANIFEST_DIR"));
    let committed = std::fs::read_to_string(&path)?;
    let value = read_value(produced)
        .map_err(|err| std::io::Error::other(format!("the derivation's text: {err}")))?;
    let updated = replace_member(&committed, "graph", &pretty_at(&value, 1))
        .map_err(std::io::Error::other)?;
    std::fs::write(&path, &updated)?;
    Ok(updated)
}

/// `text` with the top-level `"name"` member's **value** replaced by `value`, which is
/// the braces and what is between them — no separator, no trailing newline.
///
/// Everything outside the member is preserved verbatim: the sibling member's bytes, and
/// the root's own braces. The `: ` separator and the newline after the member are written
/// here rather than read from `text`, so a file this function has already written is
/// rewritten byte-identically instead of accumulating a separator's worth of drift per
/// run.
///
/// Ponytail: `find("\"graph\":")` takes the FIRST `"graph":` anywhere in the file, not the
/// top-level member the line above names, so the assertion is position-insensitive: it
/// passes on the committed fixture only because that file's first `"graph":` is the member
/// it means. It fails on any fixture whose first `"graph":` is something else — a
/// `graph.json` carrying `"graph":` inside another object, or an earlier nested structure —
/// which would then be rewritten as if it were the member. Escape hatch: none; the caller
/// passes the whole document text it read.
fn replace_member(text: &str, name: &str, value: &str) -> Result<String, String> {
    let key = format!("\"{name}\":");
    let at = text
        .find(&key)
        .ok_or_else(|| format!("no `{name}` member"))?;
    let after_key = at + key.len();
    let open = after_key + text[after_key..].len() - text[after_key..].trim_start().len();
    let end = matching_brace(text, open).ok_or_else(|| format!("`{name}` is unterminated"))?;
    // Exactly one newline separates the member from whatever follows it, however many the
    // file it read had — so a member that was ever hand-edited does not accumulate a
    // blank line per regeneration.
    let after = text[end..].trim_start_matches('\n');
    Ok(format!("{}{key} {}\n{after}", &text[..at], value.trim()))
}

/// The index just past the `}` closing the `{` at `open`, skipping braces inside strings.
fn matching_brace(text: &str, open: usize) -> Option<usize> {
    let mut depth = 0usize;
    let mut in_string = false;
    let mut escaped = false;
    for (at, byte) in text.as_bytes().iter().enumerate().skip(open) {
        if in_string {
            if escaped {
                escaped = false;
            } else if *byte == b'\\' {
                escaped = true;
            } else if *byte == b'"' {
                in_string = false;
            }
            continue;
        }
        match byte {
            b'"' => in_string = true,
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(at + 1);
                }
            }
            _ => {}
        }
    }
    None
}

/// The fixture's own formatting: two spaces per depth, keys sorted by bytes at every
/// depth, arrays in derived order, one trailing newline. The shape the committed file
/// already has, so a regeneration with nothing changed is a no-op on disk.
fn pretty_at(value: &JsonValue, depth: usize) -> String {
    let mut out = String::new();
    write_pretty(&mut out, value, depth);
    out.push('\n');
    out
}

fn write_pretty(out: &mut String, value: &JsonValue, depth: usize) {
    match value {
        // `to_json_value` is the contract's own writer, so a null, a bool, a number and an
        // escaped string are spelled by one rule rather than by a second one here.
        JsonValue::List(items) if !items.is_empty() => write_list(out, items, depth),
        JsonValue::Map(members) if !members.is_empty() => write_map(out, members, depth),
        other => out.push_str(&to_json_value(other)),
    }
}

fn write_list(out: &mut String, items: &[JsonValue], depth: usize) {
    out.push_str("[\n");
    for (i, item) in items.iter().enumerate() {
        if i > 0 {
            out.push_str(",\n");
        }
        indent(out, depth + 1);
        write_pretty(out, item, depth + 1);
    }
    out.push('\n');
    indent(out, depth);
    out.push(']');
}

/// Sorted by key, the reader having refused a duplicate key: the file has one member
/// order, and it is the canonical one, whatever order it arrived in.
fn write_map(out: &mut String, members: &[(String, JsonValue)], depth: usize) {
    // Sorted by key, with a stable sort (D5): the reader has refused a duplicate key, so no
    // two rows can share one and the order of a re-serialization cannot be observed here.
    let mut rows: Vec<(&str, &JsonValue)> = members.iter().map(|(k, v)| (k.as_str(), v)).collect();
    rows.sort_by(|a, b| a.0.cmp(b.0));
    out.push_str("{\n");
    for (i, (key, member)) in rows.iter().enumerate() {
        if i > 0 {
            out.push_str(",\n");
        }
        indent(out, depth + 1);
        out.push_str(&to_json_value(&JsonValue::Text((*key).to_owned())));
        out.push_str(": ");
        write_pretty(out, member, depth + 1);
    }
    out.push('\n');
    indent(out, depth);
    out.push('}');
}

fn indent(out: &mut String, depth: usize) {
    for _ in 0..depth {
        out.push_str("  ");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn replacing_a_member_leaves_every_other_byte_alone() {
        let text = "{\n  \"ingest\": {\"a\": 1},\n  \"graph\": {\"stale\": true}\n}\n";
        let out = replace_member(text, "graph", "{\n    \"fresh\": 1\n  }").expect("present");
        assert_eq!(
            out,
            "{\n  \"ingest\": {\"a\": 1},\n  \"graph\": {\n    \"fresh\": 1\n  }\n}\n"
        );
    }

    #[test]
    fn rewriting_a_member_twice_is_the_same_bytes_once() {
        // The generator runs on a file it may itself have written, so a second run must
        // be a no-op rather than a separator's worth of drift.
        let text = "{\n  \"ingest\": {\"a\": 1},\n  \"graph\": {\"stale\": true}\n}\n";
        let once = replace_member(text, "graph", "{\n    \"fresh\": 1\n  }").expect("present");
        let twice = replace_member(&once, "graph", "{\n    \"fresh\": 1\n  }").expect("present");
        assert_eq!(once, twice);
    }

    #[test]
    fn a_brace_inside_a_string_does_not_end_the_member() {
        // The member's real value reaches past the `}` inside the string, so a naive
        // brace count would truncate the value and keep a tail of the old one.
        let text = "{\"graph\": {\"label\": \"a}b\", \"n\": 1}, \"after\": 2}";
        let out = replace_member(text, "graph", "{\"fresh\": 1}").expect("present");
        assert_eq!(out, "{\"graph\": {\"fresh\": 1}\n, \"after\": 2}");
    }

    #[test]
    fn a_member_already_separated_by_a_blank_line_keeps_exactly_one() {
        // A hand-edited file can carry two; the generator normalises to one rather than
        // leaving the drift in place or adding to it.
        let text = "{\n  \"graph\": {\"a\": 1}\n\n}\n";
        let out = replace_member(text, "graph", "{\"b\": 2}").expect("present");
        assert_eq!(out, "{\n  \"graph\": {\"b\": 2}\n}\n");
    }

    #[test]
    fn an_absent_member_is_an_error_rather_than_a_silent_no_op() {
        let why = replace_member("{}", "graph", "{}").expect_err("absent");
        assert!(why.contains("graph"), "{why}");
    }

    #[test]
    fn the_pretty_form_is_the_files_own_two_space_sorted_shape() {
        let value = read_value(r#"{"b":1,"a":[{"z":null,"y":[]}],"c":{},"d":"x\"y"}"#)
            .expect("JSON is well-formed");
        assert_eq!(
            pretty_at(&value, 0).trim_end(),
            concat!(
                "{\n",
                "  \"a\": [\n",
                "    {\n",
                "      \"y\": [],\n",
                "      \"z\": null\n",
                "    }\n",
                "  ],\n",
                "  \"b\": 1,\n",
                "  \"c\": {},\n",
                "  \"d\": \"x\\\"y\"\n",
                "}"
            )
        );
    }

    #[test]
    fn a_whole_number_and_its_float_spelling_are_one_text() {
        let value = read_value(r#"{"strength":2,"weight":0.5,"version":1700000001}"#)
            .expect("JSON is well-formed");
        assert_eq!(
            pretty_at(&value, 0).trim_end(),
            "{\n  \"strength\": 2,\n  \"version\": 1700000001,\n  \"weight\": 0.5\n}"
        );
    }
}
