//! The TypeScript half of codegen: a JSON Schema in, declarations out.
//!
//! Split out of `codegen.rs` by the house's 300-line limit, and because it is a different
//! half: `codegen.rs` knows *which* files exist, this knows how to spell one. Types only —
//! the generated file declares shapes and ships zero runtime bytes, so every function here
//! returns text and nothing evaluates it.
//!
//! The mapping is deliberately narrow. A JSON Schema has a dozen keywords this does not
//! read, and every one it cannot read becomes `unknown`: a generated type that says
//! `unknown` is wrong in a way a compiler will find, while a generated type that *guesses*
//! is wrong in a way nothing will. Adding a keyword here is a change to a public artefact,
//! so each one is added with a test that pins its spelling.

pub(super) use serde_json::{Map, Value};
use super::json_schema as schema_for_header;
use super::layout_params_schema;

/// TypeScript declarations for the same types, derived from [`json_schema`].
pub fn typescript() -> String {
    let schema = schema_for_header();
    let mut out = String::from("// Generated by graph-contract codegen. Do not edit.\n");
    let title = schema["title"].as_str().unwrap_or("Root");
    out.push_str(&declaration(title, &schema));
    if let Some(defs) = schema["$defs"].as_object() {
        for (name, def) in defs {
            out.push_str(&declaration(name, def));
        }
    }
    out
}

/// TypeScript declarations for the layout-parameter schema, derived from
/// [`layout_params_schema`] by the same path as [`typescript`]: declarations only,
/// zero runtime bytes. Its types are named `LayoutParamSpec`/`LayoutParamKind`
/// rather than `ParamSpec`/`ParamKind`, which the studio already exports for its own
/// knobs with different meanings (`packages/graph-studio/src/actions/registry.ts`).
pub fn params_typescript() -> String {
    let schema = layout_params_schema();
    let mut out = String::from("// Generated by graph-contract codegen. Do not edit.\n");
    let title = schema["title"].as_str().unwrap_or("Root");
    out.push_str(&declaration(title, &schema));
    if let Some(defs) = schema["$defs"].as_object() {
        for (name, def) in defs {
            out.push_str(&declaration(name, def));
        }
    }
    out
}

pub(super) fn declaration(name: &str, def: &Value) -> String {
    let doc = doc_comment(def, "");
    if let Some(variants) = def["oneOf"].as_array() {
        let consts: Vec<String> = variants
            .iter()
            .map(|v| format!("\"{}\"", v["const"].as_str().unwrap_or("")))
            .collect();
        return format!("\n{doc}export type {name} = {};\n", consts.join(" | "));
    }
    // A fieldless enum with renamed variants lands as `enum: [...]` rather than
    // `oneOf: [{const}]`; both are a closed set of string literals, so both become a
    // union type rather than `unknown`.
    if let Some(values) = def["enum"].as_array() {
        let consts: Vec<String> = values
            .iter()
            .map(|v| format!("\"{}\"", v.as_str().unwrap_or("")))
            .collect();
        if consts.len() == values.len() {
            return format!("\n{doc}export type {name} = {};\n", consts.join(" | "));
        }
    }
    let empty = Map::new();
    let props = def["properties"].as_object().unwrap_or(&empty);
    let required: Vec<&str> = def["required"]
        .as_array()
        .map(|r| r.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let mut body = String::new();
    for (field, spec) in props {
        let optional = if required.contains(&field.as_str()) {
            ""
        } else {
            "?"
        };
        body.push_str(&format!(
            "{}  {field}{optional}: {};\n",
            doc_comment(spec, "  "),
            ts_type(spec)
        ));
    }
    format!("\n{doc}export interface {name} {{\n{body}}}\n")
}

pub(super) fn ts_type(spec: &Value) -> String {
    if let Some(reference) = spec["$ref"].as_str() {
        return reference
            .rsplit('/')
            .next()
            .unwrap_or("unknown")
            .to_string();
    }
    match spec["type"].as_str() {
        Some("integer" | "number") => "number".into(),
        Some("string") => "string".into(),
        Some("boolean") => "boolean".into(),
        Some("array") => format!("{}[]", ts_type(&spec["items"])),
        _ => "unknown".into(),
    }
}

pub(super) fn doc_comment(spec: &Value, indent: &str) -> String {
    spec["description"]
        .as_str()
        .map(|d| format!("{indent}/** {d} */\n"))
        .unwrap_or_default()
}
