//! The TypeScript half of codegen: a JSON Schema in, declarations out.
//!
//! Split out of `codegen.rs` by the house's 300-line limit, and because it is a different
//! half: `codegen.rs` knows *which* files exist, this knows how to spell one. Types only —
//! the generated file declares shapes and ships zero runtime bytes, so every function here
//! returns text and nothing evaluates it.
//!
//! The mapping is deliberately narrow. A JSON Schema has a dozen keywords this does not
//! read, and every one it cannot read becomes `unknown`: a generated type that says
//! `unknown` is wrong in a way a compiler will find, while one that *guesses* is wrong in a
//! way nothing will. Adding a keyword here is a change to a public artefact, so each one
//! arrives with a test that pins its spelling.

use super::{json_schema, layout_params_schema};
use serde_json::{Map, Value};

/// The banner every generated TypeScript file starts with.
const BANNER: &str = "// Generated by graph-contract codegen. Do not edit.\n";

/// TypeScript declarations for the snapshot header, derived from [`json_schema`].
pub fn typescript() -> String {
    declarations(&json_schema())
}

/// TypeScript declarations for the layout-parameter schema, derived from
/// [`layout_params_schema`] by the same path as [`typescript`].
pub fn params_typescript() -> String {
    declarations(&layout_params_schema())
}

/// One schema's declarations: the root under its own title, then every `$defs` member in
/// the order the schema lists them.
///
/// The order is the schema's, not sorted: `$defs` is a JSON object and `serde_json` keeps
/// insertion order for it, so the file is reproducible byte for byte from the schema — and
/// re-sorting here would move a declaration a reader has already diffed against.
fn declarations(schema: &Value) -> String {
    let mut out = String::from(BANNER);
    let title = schema["title"].as_str().unwrap_or("Root");
    out.push_str(&declaration(title, schema));
    if let Some(defs) = schema["$defs"].as_object() {
        for (name, def) in defs {
            out.push_str(&declaration(name, def));
        }
    }
    out
}

/// One declaration: a closed set of string literals becomes a union `type`, anything with
/// properties becomes an `interface`. A schema with neither is a shape the generator cannot
/// spell, and says so with an empty interface rather than guessing.
pub(super) fn declaration(name: &str, def: &Value) -> String {
    let doc = doc_comment(def, "");
    if let Some(literals) = literals(def) {
        return format!("\n{doc}export type {name} = {};\n", literals.join(" | "));
    }
    let empty = Map::new();
    let props = def["properties"].as_object().unwrap_or(&empty);
    let required: Vec<&str> = def["required"]
        .as_array()
        .map(|r| r.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let mut body = String::new();
    for (field, spec) in props {
        let optional = if required.contains(&field.as_str()) {
            ""
        } else {
            "?"
        };
        body.push_str(&format!(
            "{}  {field}{optional}: {};\n",
            doc_comment(spec, "  "),
            ts_type(spec)
        ));
    }
    format!("\n{doc}export interface {name} {{\n{body}}}\n")
}

/// The string literals a closed-set schema names, if it is one.
///
/// Two spellings reach here and both mean the same thing: `oneOf: [{const: …}]`, which is
/// what a unit-variant Rust enum derives to, and `enum: [...]`, which is what a fieldless
/// renamed enum derives to. Both are a union of literals rather than `unknown`, and the
/// second is only accepted when *every* member is a string — a mixed `enum` is not a closed
/// set of literals and guessing at it would be worse than `unknown`.
fn literals(def: &Value) -> Option<Vec<String>> {
    if let Some(variants) = def["oneOf"].as_array() {
        return Some(
            variants
                .iter()
                .map(|v| format!("\"{}\"", v["const"].as_str().unwrap_or("")))
                .collect(),
        );
    }
    let values = def["enum"].as_array()?;
    let mut out = Vec::with_capacity(values.len());
    for value in values {
        out.push(format!("\"{}\"", value.as_str()?));
    }
    Some(out)
}

/// One JSON Schema type, as TypeScript. The mapping is total and every branch that is not
/// read is `unknown`: see the module doc for why guessing would be the wrong failure.
pub(super) fn ts_type(spec: &Value) -> String {
    if let Some(reference) = spec["$ref"].as_str() {
        return reference.rsplit('/').next().unwrap_or("unknown").to_string();
    }
    // `anyOf`/`oneOf` on a *property* is a union of what it allows, and `null` is one of
    // the arms for every optional field — so the arms are joined and `null` becomes the
    // TypeScript `null` rather than `unknown`.
    for keyword in ["anyOf", "oneOf"] {
        if let Some(arms) = spec[keyword].as_array() {
            let joined: Vec<String> = arms.iter().map(ts_type).collect();
            return joined.join(" | ");
        }
    }
    if spec["type"].as_str() == Some("null") {
        return "null".into();
    }
    match spec["type"].as_str() {
        Some("integer" | "number") => "number".into(),
        Some("string") => "string".into(),
        Some("boolean") => "boolean".into(),
        Some("array") => return array_type(spec),
        Some("object") => return object_type(spec),
        _ => "unknown".into(),
    }
}

/// An array's TypeScript: `T[]`, or `(T | U)[]` when the element type is a union — the
/// parentheses are not optional, and without them `a | b[]` types the *union* as an array
/// of `b`.
fn array_type(spec: &Value) -> String {
    let element = ts_type(&spec["items"]);
    if element.contains('|') {
        return format!("({element})[]");
    }
    format!("{element}[]")
}

/// An object's TypeScript. A schema with `additionalProperties` names the type of *every*
/// member, which is a `Record<string, T>`; one without is a shape with no known members,
/// which stays `unknown` rather than becoming an index signature nothing asked for.
fn object_type(spec: &Value) -> String {
    match spec["additionalProperties"].as_object() {
        Some(extra) if extra.get("type").is_some() => {
            format!("Record<string, {}>", ts_type(&spec["additionalProperties"]))
        }
        _ => "unknown".into(),
    }
}

/// A `/** … */` line for a schema's `description`, indented by `indent`, or nothing.
pub(super) fn doc_comment(spec: &Value, indent: &str) -> String {
    spec["description"]
        .as_str()
        .map(|d| format!("{indent}/** {d} */\n"))
        .unwrap_or_default()
}