//! graph-contract — the single source of truth for the graph-motor wire format.
//!
//! The geometry vocabulary (`prompt.md` §4), the format version every reader checks,
//! and a snapshot's two faces: the binary face the hash is taken over
//! (`docs/contract/binary-layout.md`, authoritative) and the canonical JSON face any
//! third-party frontend reads. Dependency-free by default, so graph-core and graph-wasm
//! can write both faces. With the `codegen` feature it also emits the JSON Schemas and
//! the TypeScript types, derived from Rust types so they cannot drift from the code.

pub mod binary;
pub mod canonical_json;
pub mod geometry;
pub mod ingest;
pub mod notes;
pub mod params;
pub mod snapshot;
pub mod version;

/// JSON Schema and TypeScript emitted from the contract types. Types only: the
/// generated TypeScript declares shapes and ships **zero runtime bytes** — no
/// validator, no enum objects, nothing a bundler would keep.
#[cfg(feature = "codegen")]
pub mod codegen {
    use serde_json::{Map, Value};

    /// Where the header's generated files are committed, relative to the workspace root.
    pub const GENERATED_DIR: &str = "crates/graph-contract/generated";

    /// Where the JSON face's schema is committed, relative to the workspace root.
    pub const SNAPSHOT_SCHEMA: &str = "docs/contract/snapshot-schema.json";

    /// Where the ingest contract's schema is committed, relative to the workspace root.
    pub const INGEST_SCHEMA: &str = "docs/contract/ingest-schema.json";

    /// Every generated file: its path from the workspace root and its exact contents.
    /// Committed, so a change to the contract types shows up as a diff in review.
    pub fn outputs() -> [(String, String); 6] {
        [
            (
                format!("{GENERATED_DIR}/snapshot-header.schema.json"),
                format!("{:#}\n", json_schema()),
            ),
            (
                format!("{GENERATED_DIR}/snapshot-header.d.ts"),
                typescript(),
            ),
            (
                SNAPSHOT_SCHEMA.to_owned(),
                format!("{:#}\n", snapshot_schema()),
            ),
            (INGEST_SCHEMA.to_owned(), format!("{:#}\n", ingest_schema())),
            (
                format!("{GENERATED_DIR}/layout-params.schema.json"),
                format!("{:#}\n", layout_params_schema()),
            ),
            (
                format!("{GENERATED_DIR}/layout-params.d.ts"),
                params_typescript(),
            ),
        ]
    }

    /// The JSON Schema (draft 2020-12) of one layout's published parameters: the schema
    /// a frontend reads to draw a control per parameter
    /// (`docs/decisions/layout-params.md`).
    pub fn layout_params_schema() -> Value {
        schemars::schema_for!(crate::canonical_json::schema::LayoutParamsSchema).to_value()
    }

    /// The JSON Schema (draft 2020-12) of the ingest contract: declared roles and
    /// records, the neutral front of the pipeline (`crates/graph-contract/src/ingest.rs`).
    pub fn ingest_schema() -> Value {
        crate::ingest::schema::schema()
    }

    /// The JSON Schema (draft 2020-12) of the canonical JSON face: a whole snapshot.
    pub fn snapshot_schema() -> Value {
        schemars::schema_for!(crate::canonical_json::schema::Snapshot).to_value()
    }

    /// The JSON Schema (draft 2020-12) of the snapshot header and everything it references.
    pub fn json_schema() -> Value {
        schemars::schema_for!(crate::snapshot::SnapshotHeader).to_value()
    }

    /// TypeScript declarations for the same types, derived from [`json_schema`].
    pub fn typescript() -> String {
        let schema = json_schema();
        let mut out = String::from("// Generated by graph-contract codegen. Do not edit.\n");
        let title = schema["title"].as_str().unwrap_or("Root");
        out.push_str(&declaration(title, &schema));
        if let Some(defs) = schema["$defs"].as_object() {
            for (name, def) in defs {
                out.push_str(&declaration(name, def));
            }
        }
        out
    }

    /// TypeScript declarations for the layout-parameter schema, derived from
    /// [`layout_params_schema`] by the same path as [`typescript`]: declarations only,
    /// zero runtime bytes. Its types are named `LayoutParamSpec`/`LayoutParamKind`
    /// rather than `ParamSpec`/`ParamKind`, which the studio already exports for its own
    /// knobs with different meanings (`packages/graph-studio/src/actions/registry.ts`).
    pub fn params_typescript() -> String {
        let schema = layout_params_schema();
        let mut out = String::from("// Generated by graph-contract codegen. Do not edit.\n");
        let title = schema["title"].as_str().unwrap_or("Root");
        out.push_str(&declaration(title, &schema));
        if let Some(defs) = schema["$defs"].as_object() {
            for (name, def) in defs {
                out.push_str(&declaration(name, def));
            }
        }
        out
    }

    fn declaration(name: &str, def: &Value) -> String {
        let doc = doc_comment(def, "");
        if let Some(variants) = def["oneOf"].as_array() {
            let consts: Vec<String> = variants
                .iter()
                .map(|v| format!("\"{}\"", v["const"].as_str().unwrap_or("")))
                .collect();
            return format!("\n{doc}export type {name} = {};\n", consts.join(" | "));
        }
        // A fieldless enum with renamed variants lands as `enum: [...]` rather than
        // `oneOf: [{const}]`; both are a closed set of string literals, so both become a
        // union type rather than `unknown`.
        if let Some(values) = def["enum"].as_array() {
            let consts: Vec<String> = values
                .iter()
                .map(|v| format!("\"{}\"", v.as_str().unwrap_or("")))
                .collect();
            if consts.len() == values.len() {
                return format!("\n{doc}export type {name} = {};\n", consts.join(" | "));
            }
        }
        let empty = Map::new();
        let props = def["properties"].as_object().unwrap_or(&empty);
        let required: Vec<&str> = def["required"]
            .as_array()
            .map(|r| r.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        let mut body = String::new();
        for (field, spec) in props {
            let optional = if required.contains(&field.as_str()) {
                ""
            } else {
                "?"
            };
            body.push_str(&format!(
                "{}  {field}{optional}: {};\n",
                doc_comment(spec, "  "),
                ts_type(spec)
            ));
        }
        format!("\n{doc}export interface {name} {{\n{body}}}\n")
    }

    fn ts_type(spec: &Value) -> String {
        if let Some(reference) = spec["$ref"].as_str() {
            return reference
                .rsplit('/')
                .next()
                .unwrap_or("unknown")
                .to_string();
        }
        match spec["type"].as_str() {
            Some("integer" | "number") => "number".into(),
            Some("string") => "string".into(),
            Some("boolean") => "boolean".into(),
            Some("array") => format!("{}[]", ts_type(&spec["items"])),
            _ => "unknown".into(),
        }
    }

    fn doc_comment(spec: &Value, indent: &str) -> String {
        spec["description"]
            .as_str()
            .map(|d| format!("{indent}/** {d} */\n"))
            .unwrap_or_default()
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn schema_pins_every_wire_integer_to_uint32() {
            let schema = json_schema();
            for field in ["stage_count", "node_count", "edge_count"] {
                assert_eq!(schema["properties"][field]["format"], "uint32", "{field}");
            }
            let stage_count = &schema["properties"]["stage_count"];
            assert_eq!(
                (&stage_count["minimum"], &stage_count["maximum"]),
                (&1.into(), &1.into())
            );
            for field in ["major", "minor"] {
                assert_eq!(
                    schema["$defs"]["FormatVersion"]["properties"][field]["format"],
                    "uint32"
                );
            }
        }

        #[test]
        fn schema_never_lists_a_reserved_kind_as_producible() {
            let text = json_schema().to_string();
            assert!(!text.contains("Ribbon") && !text.contains("\"Arc\""));
        }

        #[test]
        fn typescript_is_declarations_only() {
            let ts = typescript();
            assert!(
                ts.contains("export type EdgeGeometryKind = \"Line\" | \"Polyline\" | \"Curve\";")
            );
            assert!(
                ts.contains("export type NodeGeometryKind = \"Point\" | \"Circle\" | \"Box\";")
            );
            assert!(ts.contains(
                "  /** Number of nodes, and the length of every node column. */\n  node_count: number;"
            ));
            assert!(ts.contains("  version: FormatVersion;"));
            for runtime in ["const ", "function", "enum ", "class ", "=>"] {
                assert!(
                    !ts.contains(runtime),
                    "runtime construct {runtime:?} in generated TS"
                );
            }
        }

        #[test]
        fn the_committed_files_are_what_codegen_generates() {
            let committed = [
                include_str!("../generated/snapshot-header.schema.json"),
                include_str!("../generated/snapshot-header.d.ts"),
                include_str!("../../../docs/contract/snapshot-schema.json"),
                include_str!("../../../docs/contract/ingest-schema.json"),
                include_str!("../generated/layout-params.schema.json"),
                include_str!("../generated/layout-params.d.ts"),
            ];
            let stale = "stale: run `graph-cli codegen` and commit the result";
            for ((name, generated), committed) in outputs().iter().zip(committed) {
                assert_eq!(committed, generated, "{name} {stale}");
            }
            assert!(GENERATED_DIR.ends_with("graph-contract/generated"));
        }

        #[test]
        fn ts_type_maps_every_json_schema_type_it_knows() {
            use serde_json::json;
            let cases = [
                (json!({"type": "integer"}), "number"),
                (json!({"type": "number"}), "number"),
                (json!({"type": "string"}), "string"),
                (json!({"type": "boolean"}), "boolean"),
                (
                    json!({"type": "array", "items": {"type": "string"}}),
                    "string[]",
                ),
                (json!({"$ref": "#/$defs/FormatVersion"}), "FormatVersion"),
                (json!({"type": "object"}), "unknown"),
            ];
            for (spec, want) in cases {
                assert_eq!(ts_type(&spec), want, "{spec}");
            }
        }
    }
}
