//! graph-contract — the single source of truth for the graph-motor wire format.
//!
//! Types, not logic: the geometry vocabulary (`prompt.md` §4), the versioned snapshot
//! header, and the one place bytes are laid out for hashing. With the `codegen`
//! feature it also emits the JSON Schema and the TypeScript types that describe the
//! semantic face, derived from these same Rust types so the three cannot drift.

pub mod geometry;
pub mod snapshot;

/// JSON Schema and TypeScript emitted from the contract types. Types only: the
/// generated TypeScript declares shapes and ships **zero runtime bytes** — no
/// validator, no enum objects, nothing a bundler would keep.
#[cfg(feature = "codegen")]
pub mod codegen {
    use serde_json::{Map, Value};

    /// The JSON Schema (draft 2020-12) of the snapshot header and everything it references.
    pub fn json_schema() -> Value {
        schemars::schema_for!(crate::snapshot::SnapshotHeader).to_value()
    }

    /// TypeScript declarations for the same types, derived from [`json_schema`].
    pub fn typescript() -> String {
        let schema = json_schema();
        let mut out = String::from("// Generated by graph-contract codegen. Do not edit.\n");
        let title = schema["title"].as_str().unwrap_or("Root");
        out.push_str(&declaration(title, &schema));
        if let Some(defs) = schema["$defs"].as_object() {
            for (name, def) in defs {
                out.push_str(&declaration(name, def));
            }
        }
        out
    }

    fn declaration(name: &str, def: &Value) -> String {
        let doc = doc_comment(def, "");
        if let Some(variants) = def["oneOf"].as_array() {
            let consts: Vec<String> = variants
                .iter()
                .map(|v| format!("\"{}\"", v["const"].as_str().unwrap_or("")))
                .collect();
            return format!("\n{doc}export type {name} = {};\n", consts.join(" | "));
        }
        let empty = Map::new();
        let props = def["properties"].as_object().unwrap_or(&empty);
        let required: Vec<&str> = def["required"]
            .as_array()
            .map(|r| r.iter().filter_map(Value::as_str).collect())
            .unwrap_or_default();
        let mut body = String::new();
        for (field, spec) in props {
            let optional = if required.contains(&field.as_str()) {
                ""
            } else {
                "?"
            };
            body.push_str(&format!(
                "{}  {field}{optional}: {};\n",
                doc_comment(spec, "  "),
                ts_type(spec)
            ));
        }
        format!("\n{doc}export interface {name} {{\n{body}}}\n")
    }

    fn ts_type(spec: &Value) -> String {
        if let Some(reference) = spec["$ref"].as_str() {
            return reference
                .rsplit('/')
                .next()
                .unwrap_or("unknown")
                .to_string();
        }
        match spec["type"].as_str() {
            Some("integer" | "number") => "number".into(),
            Some("string") => "string".into(),
            Some("boolean") => "boolean".into(),
            Some("array") => format!("{}[]", ts_type(&spec["items"])),
            _ => "unknown".into(),
        }
    }

    fn doc_comment(spec: &Value, indent: &str) -> String {
        spec["description"]
            .as_str()
            .map(|d| format!("{indent}/** {d} */\n"))
            .unwrap_or_default()
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn schema_pins_every_wire_integer_to_uint32() {
            let schema = json_schema();
            for field in ["stage_count", "node_count", "edge_count"] {
                assert_eq!(schema["properties"][field]["format"], "uint32", "{field}");
            }
            for field in ["major", "minor"] {
                assert_eq!(
                    schema["$defs"]["FormatVersion"]["properties"][field]["format"],
                    "uint32"
                );
            }
        }

        #[test]
        fn schema_never_lists_a_reserved_kind_as_producible() {
            let text = json_schema().to_string();
            assert!(!text.contains("Ribbon") && !text.contains("\"Arc\""));
        }

        #[test]
        fn typescript_is_declarations_only() {
            let ts = typescript();
            assert!(
                ts.contains("export type EdgeGeometryKind = \"Line\" | \"Polyline\" | \"Curve\";")
            );
            assert!(
                ts.contains("export type NodeGeometryKind = \"Point\" | \"Circle\" | \"Box\";")
            );
            assert!(ts.contains("  node_count: number;"));
            assert!(ts.contains("  version: FormatVersion;"));
            for runtime in ["const ", "function", "enum ", "class ", "=>"] {
                assert!(
                    !ts.contains(runtime),
                    "runtime construct {runtime:?} in generated TS"
                );
            }
        }
    }
}
