//! What the sweep writes, and what it read off the host to write it.
//!
//! The load average is read **twice** — before the first timing and after the last — and
//! both readings go in the report next to the numbers. This host is shared, so a cell
//! measured while it was busy is not a slower cell of the same tier but a different
//! measurement, and the reader cannot tell which from the number alone.

use super::{Cell, Host, Tier};
use crate::bench::Plan;
use graph_core::layout::force::BarnesHut;
use std::path::Path;

/// `/proc/loadavg`'s first three fields, or `unavailable` where there is no `/proc`.
///
/// The `impl Fn` is the seam: the reading itself is a one-line `read_to_string`, and the
/// part worth pinning is what it does with a line it cannot parse or a file it cannot
/// open — which is the case every non-Linux host hits.
pub fn loadavg_from(read: impl Fn(&str) -> std::io::Result<String>) -> String {
    let Ok(line) = read("/proc/loadavg") else {
        return "unavailable".into();
    };
    line.split_whitespace()
        .take(3)
        .collect::<Vec<_>>()
        .join(" ")
}

/// The host this run is on: its core count and the load average at both ends of the run.
///
/// Two separate readings, taken by the caller around the timings — one reading taken once
/// and labelled twice would print the same number at both ends and hide the very thing the
/// report exists to show.
pub fn host(start: String, end: String) -> Host {
    Host {
        nproc: std::thread::available_parallelism().map_or(0, |n| n.get()),
        load_start: start,
        load_end: end,
    }
}

/// `/proc/loadavg` right now, for the reading that opens the run.
pub fn loadavg() -> String {
    loadavg_from(|path| std::fs::read_to_string(path))
}

/// The sweep's markdown: the table, the host, and every individual run behind the median.
pub fn markdown(plan: &Plan, cells: &[Cell], host: &Host) -> String {
    let mut out = String::from(
        "# Phase 11 threads — the Barnes-Hut stage under each execution tier\n\n\
         Generated by `graph-cli bench --tiers` in a release build. Every number is the \
         **whole stage** (`BarnesHut::run_with` over `TICKS` = 112 ticks), median of the \
         stated repeat count, not a single timing. `equal` is the arm's geometry against \
         the same run's serial arm: a tier that is faster and different is a faster wrong \
         answer, so a row that says otherwise is a failure, not a footnote.\n\n",
    );
    out += &format!(
        "seed {} · repeat {} · release · passes handed to the runner: {}\n\n",
        plan.seed,
        plan.repeat,
        BarnesHut::THREADED_PASSES.join(", ")
    );
    out += &table(cells);
    out += &crossover_lines(cells);
    out += &host_lines(host);
    out += "\n";
    out += PONYTAIL;
    out
}

/// The sizes the sweep measured, in ascending order and spelled as a list — read from the
/// cells rather than from the flag, and sorted **numerically**: `10000` before `220` would
/// make the sentence below it about a ladder that runs backwards.
fn measured_sizes(cells: &[Cell]) -> String {
    let mut sizes: Vec<u32> = cells.iter().map(|c| c.n).collect();
    sizes.sort_unstable();
    sizes.dedup();
    sizes
        .iter()
        .map(|n| format!("n={n}"))
        .collect::<Vec<_>>()
        .join(", ")
}

/// The crossover, read off the table rather than asserted beside it: the largest measured
/// size at which every threaded arm lost, and the smallest at which any won.
fn crossover_lines(cells: &[Cell]) -> String {
    let sizes = measured_sizes(cells);
    match super::crossover(cells) {
        Some((loss, win)) => format!(
            "## The crossover\n\nThreads lose to scalar at every measured size up to **n={loss}** \
             and win from **n={win}**. The crossover is therefore *bracketed* between those \
             two measured sizes and not located inside them: this sweep measured {sizes}. \
             `docs/decisions/tier-thresholds.md` writes its `threads_nodes` row at the first \
             winning size, which is the only claim these numbers support.\n\n",
            sizes = sizes
        ),
        None => format!(
            "## The crossover\n\nNo crossover in the measured sizes (n={sizes}): every threaded \
             arm either won or lost at all of them, so this run cannot justify a threshold \
             row either way and `tier-thresholds.md`'s stays where it was.\n\n",
            sizes = sizes
        ),
    }
}

/// One table: the median, the speedup against the serial arm at the same size, the raw
/// runs, and the byte check.
fn table(cells: &[Cell]) -> String {
    let mut out = String::from(
        "| n | tier | median ms | speedup | runs (ms) | equal to scalar |\n\
         |---:|---|---:|---:|---|---|\n",
    );
    for (cell, reference) in cells.iter().zip(references(cells)) {
        let speedup = cell
            .speedup(reference)
            .map_or("-".into(), |s| format!("{s:.2}x"));
        let runs: Vec<String> = cell.runs_ms.iter().map(|ms| format!("{ms:.2}")).collect();
        out += &format!(
            "| {} | {} | {:.2} | {speedup} | {} | {} |\n",
            cell.n,
            cell.tier.arm_name(),
            cell.median_ms(),
            runs.join(", "),
            cell.equal
        );
    }
    out += "\n";
    out
}

/// The serial cell at each size, or `None` where the sweep timed no scalar arm.
fn references(cells: &[Cell]) -> Vec<&Cell> {
    cells
        .iter()
        .map(|cell| {
            cells
                .iter()
                .find(|other| other.n == cell.n && other.tier == Tier::Scalar)
                .unwrap_or(cell)
        })
        .collect()
}

/// The machine and its load at both ends of the run, in the table's own terms.
fn host_lines(host: &Host) -> String {
    format!(
        "Host: nproc {} · load average at the start {start} · at the end {end} · build \
         profile release. The host is shared, so a busy one is a **different measurement**, \
         not a smaller one: it inflates whichever arm it lands on, and these two readings are \
         what lets the reader see which side of the ratio was loaded.\n",
        host.nproc,
        start = host.load_start,
        end = host.load_end,
    )
}

/// What a number in this file is and is not: one machine class, one build, one seed.
const PONYTAIL: &str = "\
## Ponytail (the speedup)

These speedups are a sample of **one machine class, one build and one model seed**, on a
shared host. Failing input: a host whose core count, memory bandwidth or load differs from
this one — a 16-core box that was busy while these ran, or a 4-core box, gives a different
table. Direction: a threshold read here picks a slower tier than the best available, or a
faster one than the host can deliver; both cost time and **never bytes**, because every
tier in the table is hash-equal to scalar per stage (`hashgate --tiers all`). Escape
hatch: the explicit `exec` option per call, which bypasses every threshold. \
";

/// The path a report is written to, parent directories included.
pub fn report_path(plan: &Plan) -> Option<&Path> {
    plan.out.as_deref()
}
