//! What the sweep writes, and what it read off the host to write it.
//!
//! The load average is read **twice** — before the first timing and after the last — and
//! both readings go in the report next to the numbers. This host is shared, so a cell
//! measured while it was busy is not a slower cell of the same tier but a different
//! measurement, and the reader cannot tell which from the number alone.

use super::{Cell, Host, Tier};
use crate::bench::Plan;
use graph_core::Grid;
use graph_core::Stage;
use graph_core::layout::force::{BarnesHut, YifanHu};
use graph_core::layout::{circular::ring, spiral};
use std::path::Path;

/// `/proc/loadavg`'s first three fields, or `unavailable` where there is no `/proc`.
///
/// The `impl Fn` is the seam: the reading itself is a one-line `read_to_string`, and the
/// part worth pinning is what it does with a line it cannot parse or a file it cannot
/// open — which is the case every non-Linux host hits.
pub fn loadavg_from(read: impl Fn(&str) -> std::io::Result<String>) -> String {
    let Ok(line) = read("/proc/loadavg") else {
        return "unavailable".into();
    };
    line.split_whitespace()
        .take(3)
        .collect::<Vec<_>>()
        .join(" ")
}

/// The host this run is on: its core count and the load average at both ends of the run.
///
/// Two separate readings, taken by the caller around the timings — one reading taken once
/// and labelled twice would print the same number at both ends and hide the very thing the
/// report exists to show.
pub fn host(start: String, end: String) -> Host {
    Host {
        nproc: std::thread::available_parallelism().map_or(0, |n| n.get()),
        load_start: start,
        load_end: end,
    }
}

/// `/proc/loadavg` right now, for the reading that opens the run.
pub fn loadavg() -> String {
    loadavg_from(|path| std::fs::read_to_string(path))
}

/// The sweep's markdown: the table, the host, and every individual run behind the median.
///
/// **The table names its layout on every row**, because a `--layout`-routed sweep can hold
/// several stages' rows at once and a bare `n` column would read as one ladder. A report
/// whose rows do not say which stage they belong to is the shape of a claim nobody can
/// check.
pub fn markdown(plan: &Plan, cells: &[Cell], host: &Host) -> String {
    let mut out = format!(
        "# Phase 11 threads — {} under each execution tier\n\n\
         Generated by `graph-cli bench --tiers` in a release build. Every number is the \
         **whole stage** of the layout named on its row, median of the stated repeat count, \
         not a single timing. `equal` is the arm's geometry against **that layout's own** \
         serial arm at the same size: a tier that is faster and different is a faster wrong \
         answer, so a row that says otherwise is a failure, not a footnote.\n\n",
        subject(cells),
    );
    out += &format!("seed {} · repeat {} · release\n\n", plan.seed, plan.repeat);
    out += &table(cells);
    out += &crossover_lines(cells);
    out += &host_lines(host);
    out += "\n";
    out += PONYTAIL;
    out
}

/// What the table is a measurement *of*, read off the cells: one stage named in full, or
/// the list of the stages present.
fn subject(cells: &[Cell]) -> String {
    let layouts = measured_layouts(cells);
    if layouts.len() == 1 {
        return stage_sentence(layouts[0]);
    }
    layouts
        .iter()
        .copied()
        .map(stage_sentence)
        .collect::<Vec<_>>()
        .join(" · ")
}

/// One layout's stage, in the words its own module uses — so the table says what was timed
/// rather than repeating the id.
fn stage_sentence(layout: &str) -> String {
    match layout {
        BarnesHut::ID => format!(
            "the Barnes-Hut stage (`BarnesHut::run_with` over `TICKS` = {TICKS} ticks, passes \
             handed to the runner: {})",
            BarnesHut::THREADED_PASSES.join(", ")
        ),
        YifanHu::ID => format!(
            "the Yifan-Hu multilevel force stage (`YifanHu::run_with`): the hierarchy and every \
             level's settle over the same three gathered passes, `TICKS` = {TICKS} ticks on the \
             coarsest level plus 48 per refinement, so the tick budget is `{TICKS} + 48 × levels` \
             and the level count is whatever the greedy coarsening reached — coarsening and \
             prolongation are serial by nature and are in every arm (passes handed to the \
             runner: {})",
            BarnesHut::THREADED_PASSES.join(", ")
        ),
        Grid::ID => "the grid lattice (`Grid::run_with`, one `f32` product per coordinate, no \
                     reduction to divide)"
            .into(),
        ring::ID => "the closed ring (`circular::ring::run_with`, one `libm` cosine and sine \
                     per node over a serial `coords` merge)"
            .into(),
        spiral::ID => "the archimedean spiral (`spiral::run_with`, the default branch; the \
                       equidistant one is serial by nature and is never threaded)"
            .into(),
        other => other.to_string(),
    }
}

/// `graph_core::stage::topology`'s tick count, the same figure `BarnesHut::run_with` runs,
/// so the sentence cannot drift from the stage it describes.
const TICKS: u32 = 112;

/// The layouts the sweep measured, in first-seen order and deduplicated — read from the
/// cells rather than from the flag, so the report cannot claim a stage it holds no row for.
fn measured_layouts(cells: &[Cell]) -> Vec<&'static str> {
    let mut out: Vec<&'static str> = Vec::new();
    for cell in cells {
        if !out.contains(&cell.layout) {
            out.push(cell.layout);
        }
    }
    out
}

/// The sizes the sweep measured for `layout`, ascending and spelled as a list — sorted
/// **numerically**: `10000` before `220` would make the sentence below it about a ladder
/// that runs backwards.
fn measured_sizes(cells: &[Cell], layout: &str) -> String {
    let mut sizes: Vec<u32> = cells
        .iter()
        .filter(|c| c.layout == layout)
        .map(|c| c.n)
        .collect();
    sizes.sort_unstable();
    sizes.dedup();
    sizes
        .iter()
        .map(|n| format!("n={n}"))
        .collect::<Vec<_>>()
        .join(", ")
}

/// The crossover, read off the table rather than asserted beside it: the largest measured
/// size at which every threaded arm lost, and the smallest at which any won. **One bracket
/// per layout** — the two stages have nothing to do with each other's crossover, and a
/// single bracket over a two-layout table would compare one layout's arms against another's
/// scalar arm.
fn crossover_lines(cells: &[Cell]) -> String {
    let mut out = String::from("## The crossover\n\n");
    for layout in measured_layouts(cells) {
        out += &bracket(cells, layout, &measured_sizes(cells, layout));
    }
    out += "\n";
    out
}

/// One layout's bracket, or the sentence that says there is not one to write.
fn bracket(cells: &[Cell], layout: &str, sizes: &str) -> String {
    let own: Vec<Cell> = cells
        .iter()
        .filter(|c| c.layout == layout)
        .cloned()
        .collect();
    match super::crossover(&own) {
        // Both keys carry the same layout: `own` is already one layout's cells.
        Some(((loss_layout, loss), (_, win))) => format!(
            "`{loss_layout}` loses to scalar at every measured size up to **n={loss}** and wins \
             from **n={win}**. The crossover is therefore *bracketed* between those two \
             measured sizes and not located inside them: this sweep measured {sizes}. \
             `docs/decisions/tier-thresholds.md` writes its `threads_nodes` row at the first \
             winning size, which is the only claim these numbers support.\n\n"
        ),
        None => format!(
            "`{layout}` shows no crossover in the measured sizes ({sizes}): every threaded arm \
             either won or lost at all of them, so this run cannot justify a threshold row \
             either way and `tier-thresholds.md`'s stays where it was.\n\n"
        ),
    }
}

/// One table: the layout, the median, the speedup against **that layout's** serial arm at
/// the same size, the raw runs, and the byte check.
fn table(cells: &[Cell]) -> String {
    let mut out = String::from(
        "| layout | n | tier | median ms | speedup | runs (ms) | equal to scalar |\n\
         |---|---:|---|---:|---:|---|---|\n",
    );
    for (cell, reference) in cells.iter().zip(references(cells)) {
        let speedup = cell
            .speedup(reference)
            .map_or("-".into(), |s| format!("{s:.2}x"));
        let runs: Vec<String> = cell.runs_ms.iter().map(|ms| format!("{ms:.2}")).collect();
        out += &format!(
            "| `{}` | {} | {} | {:.2} | {speedup} | {} | {} |\n",
            cell.layout,
            cell.n,
            cell.tier.arm_name(),
            cell.median_ms(),
            runs.join(", "),
            cell.equal
        );
    }
    out += "\n";
    out
}

/// The serial cell of the **same layout at the same size**, or the cell itself where the
/// sweep timed no scalar arm. Matching on the layout is what keeps one stage's serial arm
/// from becoming another stage's reference.
fn references(cells: &[Cell]) -> Vec<&Cell> {
    cells
        .iter()
        .map(|cell| {
            cells
                .iter()
                .find(|other| {
                    other.layout == cell.layout && other.n == cell.n && other.tier == Tier::Scalar
                })
                .unwrap_or(cell)
        })
        .collect()
}

/// The machine and its load at both ends of the run, in the table's own terms.
fn host_lines(host: &Host) -> String {
    format!(
        "Host: nproc {} · load average at the start {start} · at the end {end} · build \
         profile release. The host is shared, so a busy one is a **different measurement**, \
         not a smaller one: it inflates whichever arm it lands on, and these two readings are \
         what lets the reader see which side of the ratio was loaded.\n",
        host.nproc,
        start = host.load_start,
        end = host.load_end,
    )
}

/// What a number in this file is and is not: one machine class, one build, one seed.
const PONYTAIL: &str = "\
## Ponytail (the speedup)

These speedups are a sample of **one machine class, one build and one model seed**, on a
shared host. Failing input: a host whose core count, memory bandwidth or load differs from
this one — a 16-core box that was busy while these ran, or a 4-core box, gives a different
table. Direction: a threshold read here picks a slower tier than the best available, or a
faster one than the host can deliver; both cost time and **never bytes**, because every
tier in the table is hash-equal to scalar per stage (`hashgate --tiers all`). Escape
hatch: the explicit `exec` option per call, which bypasses every threshold.

Three further limits, one per question this branch asked. The closed-form point layouts are
**one gather over a serial merge**, so Amdahl bounds every speedup here at the gather's
share of a stage that is short: at n=220 the thread spawn and the serial merge cost more
than the work they divide, and a `speedup` below 1.0 there is the measurement working, not
a regression to be tuned away. A serial arm that reads **0.00 ms** is below the clock's
resolution, so its row's `speedup` is a ratio against a number the timer rounded to nothing
— read the *threads* rows on that line, which are large enough to time, and read the scalar
side as faster than the clock can say. And `GM_MUTATE_SPLIT_RESCALE` is the
control for the *merge*: it turns the gate red on `layout.circular.ring` and
`layout.spiral` and nowhere else, which is what proves the threaded arms recomputed it;
`GM_MUTATE_GRID_SPACING` is the grid's *pass* control, a parameter that moves every arm
alike and so proves the stage is hashed and compared at all. Neither one stands in for the
other, and a stage with no merge has no merge control to have. \
";

/// The path a report is written to, parent directories included.
pub fn report_path(plan: &Plan) -> Option<&Path> {
    plan.out.as_deref()
}
