/**
 * Extract the `--osio-*` custom-property declarations from the osionos host
 * stylesheet into a plain, dependency-free stylesheet.
 *
 * WHY THIS EXISTS (verification harness, not shipped code)
 * -------------------------------------------------------
 * The whole point of the visual-parity check is to render the graph against the
 * host's REAL token values. global.css is a Tailwind v4 entry (`@import
 * "tailwindcss"`, `@theme`, `@layer`), so importing it into a bare harness would
 * drag in a build pipeline the engine package has no reason to depend on.
 *
 * But the canvas never consumes Tailwind. `core/theme/tokens.ts` reads its
 * colours with `getComputedStyle(el).getPropertyValue("--osio-graph-*")` at
 * runtime — plain custom properties, resolved through the cascade. So the exact
 * token surface is a flat set of declarations under a handful of selectors, and
 * extracting it verbatim is a faithful reproduction of what the engine sees.
 *
 * The selectors are preserved exactly, so the
 * `[data-palette="nord"][data-theme="dark"]` > `[data-theme=dark]` > `:root`
 * specificity order the host relies on survives the extraction.
 *
 * Non-declaration at-rules (`@import`, `@plugin`, `@theme`, `@layer`) are dropped
 * along with every non-custom-property value: the canvas reads no font, no
 * spacing scale, and no utility class.
 */

import { readFileSync, writeFileSync } from "node:fs";

const SRC = process.argv[2];
const OUT = process.argv[3];
const PREFIX = "--osio-";

if (!SRC || !OUT) {
  console.error("usage: node extract-tokens.mjs <global.css> <out.css>");
  process.exit(1);
}
const css = readFileSync(SRC, "utf8");
const out = [
  "/* GENERATED by verify/extract-tokens.mjs — do not edit.",
  " * Verbatim `--osio-*` custom properties from the osionos host stylesheet,",
  " * with selectors preserved so the palette/theme cascade is unchanged.",
  " * This is the surface `core/theme/tokens.ts` actually reads at runtime.",
  " */",
  "",
];

/** Selectors whose custom properties the graph engine can observe. */
const KEEP_SELECTOR = /:root|\[data-theme|\[data-palette/;

let keptBlocks = 0;
let keptDecls = 0;
// Strip the 42-school ASCII header comments so they don't nest confusingly.
const stripped = css.replace(/\/\*[\s\S]*?\*\//g, "");

const blockRe = /([^{}]+)\{([^{}]*)\}/g;
let m = blockRe.exec(stripped);
while (m !== null) {
  const rawSelector = m[1].trim();
  const body = m[2];
  // Only flat blocks; nested at-rules (@media, @layer) are intentionally not
  // walked — the graph token blocks in global.css are all top-level.
  if (KEEP_SELECTOR.test(rawSelector) && !rawSelector.startsWith("@")) {
    const decls = [];
    for (const line of body.split(";")) {
      const decl = line.trim();
      if (!decl) continue;
      const idx = decl.indexOf(":");
      if (idx === -1) continue;
      const prop = decl.slice(0, idx).trim();
      if (!prop.startsWith(PREFIX)) continue;
      decls.push(`  ${prop}:${decl.slice(idx + 1).trim()};`);
    }
    if (decls.length > 0) {
      out.push(`${rawSelector} {`, ...decls, "}", "");
      keptBlocks += 1;
      keptDecls += decls.length;
    }
  }
  m = blockRe.exec(stripped);
}

writeFileSync(OUT, out.join("\n"));
console.log(`blocks kept: ${keptBlocks}, declarations kept: ${keptDecls} -> ${OUT}`);
