#!/usr/bin/env bash
# service-caps-time.sh — every cap of docs/measurements/service-caps.tsv, at its cap, on the image
# (Verdict condition 2's time half, docs/reviews/review-svc-r2.md new condition 3).
#
#   scripts/service-caps-time.sh
#
# What it proves: each row of the caps table answers 200 within GRAPH_TIMEOUT_MS on the image's own
# CPU. The table was measured on the host CPU under load1 up to 38.76 and
# docs/measurements/service-caps.md "Conditions of the measurement" says so, so the time-bound caps
# have never been read against the image. One row, one container, one request per id, in the table's
# own order.
#
# The graph of a row is the one the cap ladder used, generated by the same command:
# `graph-cli bench --n <cap_n> --seed 1 --emit-scale-fixture`, which is `graph_core::seeded_model`
# (crates/graph-cli/src/bench/scale.rs), the model docs/measurements/service-caps.md names. Its m is
# about 1.5474 n, which is inside every row's cap_m; the ladder's dense 4n rung set the cap_m of the
# large rows and is not reachable through the body, so no row here is the dense rung.
#
# Two rows cannot be asked at their cap_n and are marked `reduced` with the reason:
#   - the generator's own ceiling, `graph_core::registry::MAX_BENCH_NODES` = 1 000 000. Every row
#     capped at 1 048 576 is asked at 1 000 000, 4.7% under.
#   - a graph whose m is past the cap_m that applies, which no row is expected to hit; the script
#     counts the emitted edges and halves n once if it happens.
#
# A post id is asked over an input layout, which is named here because the table names it and no
# command line reads the markdown: docs/measurements/service-caps.md:112-119, "post, over ...".
# `post.separate.grid` is the one choice: the table names `layout.packing.circle`, whose own cap is
# 2048 nodes, so that pair could only be asked at half the post's cap. It is asked over the post's
# other documented input, `layout.treemap.squarified`, which admits all 4096.
#
# Env:
#   GRAPH_TIMEOUT_MS               the pass mark, 30000 by default, passed to the container as it is.
#   SERVICE_CAPS_TIME_TIMEOUT_MS   sets the mark from outside and picks the report directory
#                                  `negctl` instead of `current`. It is the negative control: at 1 ms
#                                  every row must answer 503, which proves the row reads the time.
#
# Bodies: cached under target/service-caps-time/bodies/n<n>.json and shared by every row at that n
# (22 of the 50 rows ask at one n), which is why the negative control is not a second 10 minutes of
# generation. The generator is deterministic, so a cached body is the body the row would have built;
# an emit that is interrupted writes to a private name and is never renamed into the cache, so a
# partial file is never reused. The cache is about 900 MB.
#
# Report: target/service-caps-time/<tag>/report.tsv, one line per row, tab-separated:
#   PASS|FAIL <id> <status> <ms> <cap_n> <cap_m> <layout> <post|-> <n> <m> <source> <reduced|->,
# with `#` lines for the image, the mark, the columns and the load1 at each end of the run.
#
# Exit: 0 every row PASS · 1 any row FAILed · 2 could not run (no image, no port, no `listening`).
#
# Caveat: a timing measurement on a shared host, not a bound. One request per id, never a median, and
# the first request on a cold container pays for the page cache the body lands in; the pass mark is
# the server's own GRAPH_TIMEOUT_MS, which starts before the body is read, so the number here
# includes the upload and the ingest and not only the run. Load only makes a row slower, so a loaded
# host can turn a PASS into a FAIL and never the reverse.
set -euo pipefail

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
root=$(git -C "$here" rev-parse --show-toplevel)
cd "$root"

tsv=docs/measurements/service-caps.tsv
bodies=target/service-caps-time/bodies
tag=current
[[ -n ${SERVICE_CAPS_TIME_TIMEOUT_MS-} ]] && tag=negctl
mark=${SERVICE_CAPS_TIME_TIMEOUT_MS:-${GRAPH_TIMEOUT_MS:-30000}}
report=target/service-caps-time/$tag/report.tsv
mkdir -p "$bodies" "${report%/*}"
: >"$report"
fails=0
rows=0
name="svc-caps-time-$$-$tag"
trap 'docker rm -f "$name" >/dev/null 2>&1 || true' EXIT

# graph_core::registry::MAX_BENCH_NODES, the ceiling `graph-cli bench --n` parses against, and the
# server's own GRAPH_MAX_BODY maximum (config.rs graph_wasm_max_ingest). Both are read, not assumed,
# where the row can read them; these two live in crates and are quoted here with their sources.
max_nodes=1000000
max_body=1073741824
memory=8g

log() { printf '\033[1m[svc-caps-time]\033[0m %s\n' "$*" >&2; }
say() { printf '%s\n' "$*" >>"$report"; }
die() {
  log "$*"
  say "# could not run: $*"
  exit 2
}

# `listening` within $1 tenths of a second, or exit 2.
await_listening() {
  local tenths=$1 i
  for ((i = 0; i < tenths; i++)); do
    docker logs "$name" 2>&1 | grep -q '"event":"listening"' && return 0
    sleep 0.1
  done
  docker logs "$name" 2>&1 | tail -3 >&2 || true
  die "no listening line within $((tenths / 10))s"
}

# The cached body for $1 nodes, written by the ladder's own generator. Caveat: the cache trusts a
# file's presence, which is sound only because the generator is deterministic in (seed, n).
body_for() {
  local n=$1
  local path=$bodies/n$n.json
  if [[ ! -s $path ]]; then
    scripts/orch/gr target/release/graph-cli bench --n "$n" --seed 1 \
      --emit-scale-fixture "/w/$path.$$" >/dev/null ||
      die "graph-cli could not emit n=$n (build it: scripts/orch/gr cargo build --release -p graph-cli)"
    mv "$path.$$" "$path"
  fi
  printf '%s\n' "$path"
}

# The edges in the body for $1 nodes, as the ladder's m. Counting on a byte the fixture repeats once
# per edge, split with `tr` so no tool has to hold a 485 MB line: `grep -c` on lines, not matches.
edges_of() {
  local n=$1
  local side=$bodies/n$n.edges
  if [[ ! -s $side ]]; then
    LC_ALL=C tr 'c' '\n' <"$bodies/n$n.json" | grep -c 'hild_first' >"$side.$$"
    mv "$side.$$" "$side"
  fi
  cat "$side"
}

# One POST: the body $4 at `layout=$1` and `source=$3`, with `post=$2` when there is one (`-` for
# a layout-only row, which is what the report prints too). Sets `status` to the HTTP code (000 when
# the connection failed) and `ms` to the elapsed milliseconds.
ask() {
  local url="http://127.0.0.1:$port/v1/layout?layout=$1&source=$3" out secs
  [[ -n $2 && $2 != - ]] && url="$url&post=$2"
  out=$(curl -sS -o /dev/null -w '%{http_code} %{time_total}' \
    --max-time "$((mark / 1000 + 300))" \
    -K <(printf 'header = "Authorization: Bearer %s"\n' "$key") \
    --data-binary "@$4" "$url") || out="000 0"
  status=${out%% *}
  secs=${out##* }
  ms=$(awk -v s="$secs" 'BEGIN { printf "%d", s * 1000 }')
}

# n and m of the last request, from the server's own log line, as `<n> <m>`.
logged_size() {
  local line n m
  line=$(docker logs --tail 1 "$name" 2>&1)
  n=$(sed -nE 's/.*"n":([0-9]+),.*/\1/p' <<<"$line")
  m=$(sed -nE 's/.*"m":([0-9]+),.*/\1/p' <<<"$line")
  printf '%s %s\n' "${n:-unknown}" "${m:-unknown}"
}

# The caps table, as `id<TAB>cap_n<TAB>cap_m` per line, header dropped.
declare -A cap_n_by=() cap_m_by=()
while IFS=$'\t' read -r id cn cm; do
  [[ $id == id || -z $id ]] && continue
  cap_n_by[$id]=$cn
  cap_m_by[$id]=$cm
done <"$tsv"
((${#cap_n_by[@]} == 50)) || die "the caps table holds ${#cap_n_by[@]} rows, not 50"

# The input layout of each post id, docs/measurements/service-caps.md:112-119.
input_of() {
  case $1 in
  post.separate.grid) printf 'layout.treemap.squarified\n' ;;
  post.*) printf 'layout.grid\n' ;;
  *) printf '\n' ;;
  esac
}

image=$(scripts/service.sh image) || die "no image: scripts/service.sh build"
work=target/service-caps-time/$tag
mkdir -p "$work"
install -m 0640 /dev/null "$work/keys"
key=$(scripts/service.sh keygen svc-caps-time-gate "$work/keys") || die "keygen refused"
load_start=$(cut -d' ' -f1 /proc/loadavg)
log "image $image, mark ${mark}ms, memory $memory, load1 $load_start"

scripts/orch/drun -d --name "$name" --memory "$memory" --memory-swap "$memory" \
  --read-only --cap-drop ALL --security-opt no-new-privileges \
  --group-add "$(stat -c %g "$work/keys")" -v "$(readlink -f "$work/keys"):/run/graph/keys:ro" \
  -e GRAPH_API_KEYS_FILE=/run/graph/keys -e GRAPH_WORKERS=1 \
  -e GRAPH_MAX_BODY="$max_body" -e GRAPH_TIMEOUT_MS="$mark" \
  -p 127.0.0.1::8080 "$image" >/dev/null || die "drun refused the container"
await_listening 300
port=$(docker port "$name" 8080/tcp 2>/dev/null | head -1)
port=${port##*:}
[[ $port =~ ^[0-9]+$ ]] || die "the container published no port on 8080"
log "container $name on 127.0.0.1:$port"

say "# image $image"
say "# container memory $memory, GRAPH_WORKERS=1, GRAPH_MAX_BODY $max_body, GRAPH_TIMEOUT_MS $mark"
say "# pass when the status is 200 and the elapsed ms is under $mark"
say "# verdict id status ms cap_n cap_m layout post n m source reduced"
say "# load1 start $load_start ($(cat /proc/loadavg))"

while IFS=$'\t' read -r id cap_n cap_m; do
  [[ $id == id || -z $id ]] && continue
  rows=$((rows + 1))
  layout=$id
  post_id=-
  reduced=-
  input=$(input_of "$id")
  if [[ -n $input ]]; then
    layout=$input
    post_id=$id
    # The cap that applies is the smallest of the two ids', so the post's own cap and its input's.
    cap_n=${cap_n_by[$id]}
    [[ ${cap_n_by[$input]} -lt $cap_n ]] && cap_n=${cap_n_by[$input]}
    cap_m=${cap_m_by[$id]}
    [[ ${cap_m_by[$input]} -lt $cap_m ]] && cap_m=${cap_m_by[$input]}
  fi
  n=$cap_n
  ((n > max_nodes)) && {
    n=$max_nodes
    reduced="reduced:n>$max_nodes"
  }
  body=$(body_for "$n")
  ((body_bytes = $(stat -c %s "$body"))) || die "no body for n=$n"
  ((body_bytes > max_body)) && die "the body for n=$n is $body_bytes bytes, past GRAPH_MAX_BODY $max_body"
  m=$(edges_of "$n")
  if ((m > cap_m)); then
    n=$((n / 2))
    reduced="reduced:m>$cap_m at n=$((n * 2))"
    body=$(body_for "$n")
    m=$(edges_of "$n")
  fi
  ask "$layout" "$post_id" studio "$body"
  read -r seen_n seen_m <<<"$(logged_size)"
  log "$id: $status ${ms}ms n=$seen_n m=$seen_m ${reduced:-at cap}"
  if [[ $status == 200 && $ms -lt $mark ]]; then
    say "PASS $id $status $ms $cap_n $cap_m $layout $post_id $seen_n $seen_m studio ${reduced:--}"
  else
    say "FAIL $id $status $ms $cap_n $cap_m $layout $post_id $seen_n $seen_m studio ${reduced:--}"
    fails=$((fails + 1))
  fi
done <"$tsv"

load_end=$(cut -d' ' -f1 /proc/loadavg)
say "# load1 end $load_end ($(cat /proc/loadavg))"
say "# rows $rows, failing $fails"
log "$rows rows, $fails failing, load1 $load_start -> $load_end"
((fails == 0 && rows == 50))